disabled_rules:
  - force_cast
  - force_try
  - line_length
  - trailing_newline
  - for_where
  - redundant_string_enum_value
  - legacy_constructor
  - vertical_whitespace
  - unused_closure_parameter
  - unused_optional_binding
opt_in_rules:
included: 
  - TodoApp
excluded: 
  - Carthage
identifier_name:
  excluded:
    - id
    - vc
