disabled_rules:
  - force_try
  - line_length
opt_in_rules:
  - attributes
  - block_based_kvo
  - closure_end_indentation
included: 
  - TodoApp
excluded: 
  - Carthage
identifier_name:
  excluded:
    - id
    - vc
