disabled_rules:
  - force_cast
  - force_try
  - line_length
  - for_where
  - legacy_constructor
opt_in_rules:
included: 
  - TodoApp
excluded: 
  - Carthage
identifier_name:
  excluded:
    - id
    - vc
